exclude:
  # RDS - Performance Insights
  - aws-rds-enable-performance-insights  # Instance does not have performance insights enabled
  - aws-rds-enable-performance-insights-kms-key  # No key specified for performance insights encryption
  - aws-rds-enable-deletion-protection # RDS instances should have deletion protection enabled

  # CloudWatch Log Group - Encryption
  - aws-cloudwatch-log-group-customer-key  # Log group is not encrypted

  # ALB - HTTP listener
  - aws-elb-http-not-used  # Listener for application load balancer does not use HTTPS

  # VPC - Security Group Egress
  - aws-vpc-no-public-egress-sgr  # Security group rule allows egress to multiple public internet addresses

  # ECS - Container Insights and allowance for public access for image pull from ECR
  - aws-ec2-no-public-egress-sgr
  - aws-ecs-enable-container-insight