name: Terraform Plan on PR

on:
  pull_request:
    branches:
      - main
      - release

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.0"

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Generate tfvars from SSM Parameter Store
        run: |
          echo "Fetching terraform-variables from SSM..."

          # Default
          ENVIRONMENT="dev"

          if [[ "${GITHUB_HEAD_REF}" == "release" || "${GITHUB_REF}" == "refs/heads/release" ]]; then
            ENVIRONMENT="prod"
          fi
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV

          PARAMETER_NAME="/hello-birthday-api/$ENVIRONMENT/terraform-variables"
          terraform_vars_json=$(aws ssm get-parameter --name "$PARAMETER_NAME" --query "Parameter.Value" --output text)
          mkdir -p "${ENVIRONMENT}"
          echo "$terraform_vars_json" > "${ENVIRONMENT}/${ENVIRONMENT}.tfvars.json"

        working-directory: terraform

      - name: Parse image name and tag from dependencies.yml
        id: parse_image
        run: |
          # Extract full image string
          FULL_IMAGE=$(yq e '.["hello-birthday-api"].image' dependencies.yml)

          # Split into IMAGE (repo) and TAG (version)
          FULL_REPO=$(echo $FULL_IMAGE | cut -d':' -f1)
          IMAGE_TAG=$(echo $FULL_IMAGE | cut -d':' -f2)
          IMAGE_NAME=$(basename $FULL_REPO)

          echo "FULL_IMAGE=$FULL_IMAGE" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Pull image from GHCR
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
          docker pull ${{ env.FULL_IMAGE }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push image to ECR
        run: |
          docker tag ${{ env.FULL_IMAGE }} ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          echo "ECR_IMAGE=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: |
          if [[ "${{ github.base_ref }}" == "main" ]]; then
            terraform init -backend-config=../infrastructure/backends/backend-dev.hcl
          elif [[ "${{ github.base_ref }}" == "release" ]]; then
            terraform init -backend-config=../infrastructure/backends/backend-prod.hcl
          else
            echo "Unsupported target branch for plan"
            exit 1
          fi
        working-directory: terraform

      - name: Terraform Fmt
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Run TFLint
        run: |
          tflint --init
          tflint --call-module-type=all

      #- name: Run tfsec for DEV (Security Checks) #disabled some tfsec tests for DEV
      #run: tfsec --config-file terraform/envs/dev/.tfsec.yaml terraform/

      #- name: Run tfsec for Prod
      #  run: tfsec terraform/

      - name: Terraform Plan
        id: plan
        env:
          TF_VAR_container_image: ${{ env.ECR_IMAGE }}
        run: |
          if [[ "${{ github.base_ref }}" == "main" ]]; then
            terraform plan -no-color -var-file=dev/dev.tfvars.json -out=tfplan | tee plan.txt
          elif [[ ${{ github.base_ref }} == "release" ]]; then
            terraform plan -var-file=prod/prod.tfvars.json -out=tfplan | tee plan.txt
          fi
        working-directory: terraform

      - name: Set Plan File Name
        run: |
          echo "${{ github.sha }}" > plan-filename.txt

      - name: Upload tfplan and plan-filename.txt to S3
        run: |
          aws s3 cp terraform/tfplan s3://hello-birthday-api-tfstate/tfplans/$ENVIRONMENT/${{ github.sha }}.tfplan
          aws s3 cp plan-filename.txt s3://hello-birthday-api-tfstate/tfplans/$ENVIRONMENT/plan-filename.txt

      - name: Comment Terraform Plan on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: terraform-plan
          path: terraform/plan.txt
